//Authontication or Login actions
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const FORGETPASSWORD_REQUEST = "FORGETPASSWORD_REQUEST"
export const FORGETPASSWORD_FAIL = "FORGETPASSWORD_FAIL"
export const FORGETPASSWORD_SUCCESS = "FORGETPASSWORD_SUCCESS"