export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";

export const NEW_PASS_REQUEST = "NEW_PASS_REQUEST";
export const NEW_PASS_SUCCESS = "NEW_PASS_SUCCESS";
export const NEW_PASS_FAIL = "NEW_PASS_FAIL";

export const FORGETPASSWORD_REQUEST = "FORGETPASSWORD_REQUEST";
export const FORGETPASSWORD_FAIL = "FORGETPASSWORD_FAIL";
export const FORGETPASSWORD_SUCCESS = "FORGETPASSWORD_SUCCESS";

export const ADD_STUDENT_REQUEST = "ADD_STUDENT_REQUEST";
export const ADD_STUDENT_FAIL = "ADD_STUDENT_FAIL";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";

export const CREATE_NEW_ADMIN_REQUEST = "CREATE_NEW_ADMIN_REQUEST";
export const CREATE_NEW_ADMIN_FAIL = "CREATE_NEW_ADMIN_FAIL";
export const CREATE_NEW_ADMIN_SUCCESS = "CREATE_NEW_ADMIN_SUCCESS";

export const CREATE_FEES_STRUCTURE = "CREATE_FEES_STRUCTURE"
export const CREATE_FEES_FAILED = "CREATE_FEES_FAILED"
export const CREATE_FEES_SUCCESS = "CREATE_FEES_SUCCESS"

export const SHOW_SIDE_BAR = "SHOW_SIDE_BAR";
export const HIDE_SIDE_BAR = "HIDE_SIDE_BAR";
